nginx:
    build: ./nginx
    ports:
        - "8000:80"
        - "443:443"
    volumes:
        - ./application:/var/www/test/
    links:
        - fpm
fpm:
    image: php:7.3-fpm
    ports:
        - "9000:9000"
    volumes:
        - ./application:/var/www/test/
